naam=input("wat is jouw naam : ")
adres = input("wat is jouw adres : ")
postcode = input("wat is je postcode : ")
woonplaats = input("wat is je woonplaats : ")

print(" ----------------------------------------------------")
print(f"|  Naam      : {naam}  ")
print(f"|  Adres     : {adres} ")
print(f"|  Postcode  : {postcode} ")
print(f"|  Woonplaats: {woonplaats}  ")
print(" ----------------------------------------------------")
